// Code generated by "stringer -type ResolutionType -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResolutionAUDIO-0]
	_ = x[ResolutionSD-1]
	_ = x[ResolutionHD-2]
	_ = x[ResolutionUHD-3]
}

const _ResolutionType_name = "AUDIOSDHDUHD"

var _ResolutionType_index = [...]uint8{0, 5, 7, 9, 12}

func (i ResolutionType) String() string {
	if i < 0 || i >= ResolutionType(len(_ResolutionType_index)-1) {
		return "ResolutionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResolutionType_name[_ResolutionType_index[i]:_ResolutionType_index[i+1]]
}
