// Code generated by "stringer -type Metric -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bandwidth-0]
	_ = x[Reqcount-1]
}

const _Metric_name = "BANDWIDTHREQCOUNT"

var _Metric_index = [...]uint8{0, 9, 17}

func (i Metric) String() string {
	if i < 0 || i >= Metric(len(_Metric_index)-1) {
		return "Metric(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Metric_name[_Metric_index[i]:_Metric_index[i+1]]
}
