// Code generated by "stringer -type JsonParserStage"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JsonParserStart-0]
	_ = x[InJsonString-1]
	_ = x[InJsonQuoteString-2]
	_ = x[InJsonObject-3]
	_ = x[InJsonArray-4]
	_ = x[InJsonNumber-5]
	_ = x[InJsonBool-6]
	_ = x[InJsonNull-7]
	_ = x[JsonParserStop-8]
}

const _JsonParserStage_name = "JsonParserStartInJsonStringInJsonQuoteStringInJsonObjectInJsonArrayInJsonNumberInJsonBoolInJsonNullJsonParserStop"

var _JsonParserStage_index = [...]uint8{0, 15, 27, 44, 56, 67, 79, 89, 99, 113}

func (i JsonParserStage) String() string {
	if i < 0 || i >= JsonParserStage(len(_JsonParserStage_index)-1) {
		return "JsonParserStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JsonParserStage_name[_JsonParserStage_index[i]:_JsonParserStage_index[i+1]]
}
