// Code generated by "stringer -type MetricType -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetricBandwidth-0]
	_ = x[MetricSrcBandwidth-1]
	_ = x[MetricQps-2]
}

const _MetricType_name = "MetricBandwidthMetricSrcBandwidthMetricQps"

var _MetricType_index = [...]uint8{0, 15, 33, 42}

func (i MetricType) String() string {
	if i < 0 || i >= MetricType(len(_MetricType_index)-1) {
		return "MetricType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetricType_name[_MetricType_index[i]:_MetricType_index[i+1]]
}
