// Code generated by "stringer -type JsonParserStage"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JsonParserStart-0]
	_ = x[InJsonString-1]
	_ = x[OutJsonString-2]
	_ = x[InJsonQuoteString-3]
	_ = x[InJsonObject-4]
	_ = x[OutJsonObject-5]
	_ = x[InJsonArray-6]
	_ = x[OutJsonArray-7]
	_ = x[InJsonNumber-8]
	_ = x[InJsonBool-9]
	_ = x[OutJsonBool-10]
	_ = x[InJsonNull-11]
	_ = x[OutJsonNull-12]
	_ = x[JsonParserStop-13]
}

const _JsonParserStage_name = "JsonParserStartInJsonStringOutJsonStringInJsonQuoteStringInJsonObjectOutJsonObjectInJsonArrayOutJsonArrayInJsonNumberInJsonBoolOutJsonBoolInJsonNullOutJsonNullJsonParserStop"

var _JsonParserStage_index = [...]uint8{0, 15, 27, 40, 57, 69, 82, 93, 105, 117, 127, 138, 148, 159, 173}

func (i JsonParserStage) String() string {
	if i < 0 || i >= JsonParserStage(len(_JsonParserStage_index)-1) {
		return "JsonParserStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JsonParserStage_name[_JsonParserStage_index[i]:_JsonParserStage_index[i+1]]
}
