// Code generated by "stringer -type Business -linecomment"; DO NOT EDIT.

package repository

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BusinessCdn-0]
	_ = x[BusinessSrc-1]
}

const _Business_name = "cdnsrc"

var _Business_index = [...]uint8{0, 3, 6}

func (i Business) String() string {
	if i < 0 || i >= Business(len(_Business_index)-1) {
		return "Business(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Business_name[_Business_index[i]:_Business_index[i+1]]
}
