// Code generated by "stringer -type LogType -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CdnLogType-0]
	_ = x[SrcLogType-1]
}

const _LogType_name = "cdnsrc"

var _LogType_index = [...]uint8{0, 3, 6}

func (i LogType) String() string {
	if i < 0 || i >= LogType(len(_LogType_index)-1) {
		return "LogType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogType_name[_LogType_index[i]:_LogType_index[i+1]]
}
