// Code generated by "stringer -type Region -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegionChina-1]
}

const _Region_name = "china"

var _Region_index = [...]uint8{0, 5}

func (i Region) String() string {
	i -= 1
	if i < 0 || i >= Region(len(_Region_index)-1) {
		return "Region(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
