// Code generated by "stringer -type OpMode -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STAT_MODE-0]
	_ = x[DELETE_MODE-1]
}

const _OpMode_name = "statdelete"

var _OpMode_index = [...]uint8{0, 4, 10}

func (i OpMode) String() string {
	if i < 0 || i >= OpMode(len(_OpMode_index)-1) {
		return "OpMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpMode_name[_OpMode_index[i]:_OpMode_index[i+1]]
}
