// Code generated by "stringer -type StorageType -linecomment"; DO NOT EDIT.

package oss

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STORAGE_STANARD-0]
	_ = x[STORAGE_LOWFREQ-1]
	_ = x[STORAGE_ARCHIVE-2]
	_ = x[STORAGE_DEEPARCHIVE-3]
}

const _StorageType_name = "standardlow freqarchivedeep archive"

var _StorageType_index = [...]uint8{0, 8, 16, 23, 35}

func (i StorageType) String() string {
	if i < 0 || i >= StorageType(len(_StorageType_index)-1) {
		return "StorageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageType_name[_StorageType_index[i]:_StorageType_index[i+1]]
}
