// Code generated by "stringer -type Granularity -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Granularity1hour-0]
	_ = x[Granularity5min-1]
}

const _Granularity_name = "hour5min"

var _Granularity_index = [...]uint8{0, 4, 8}

func (i Granularity) String() string {
	if i < 0 || i >= Granularity(len(_Granularity_index)-1) {
		return "Granularity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Granularity_name[_Granularity_index[i]:_Granularity_index[i+1]]
}
