// Code generated by "stringer -type CacheStatus -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CacheHit-0]
	_ = x[CacheDynmaic-1]
	_ = x[CacheMiss-2]
	_ = x[CacheNone-3]
}

const _CacheStatus_name = "hitdynamicmissnone"

var _CacheStatus_index = [...]uint8{0, 3, 10, 14, 18}

func (i CacheStatus) String() string {
	if i < 0 || i >= CacheStatus(len(_CacheStatus_index)-1) {
		return "CacheStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CacheStatus_name[_CacheStatus_index[i]:_CacheStatus_index[i+1]]
}
