// Code generated by "stringer -type State -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FOLLOWER_STATE-0]
	_ = x[CANDIDATE_STATE-1]
	_ = x[LEADER_STATE-2]
}

const _State_name = "FOLLOWERCANDIDATELEADER"

var _State_index = [...]uint8{0, 8, 17, 23}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
